# Generated by Django 5.1.7 on 2025-03-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='varation_category',
            new_name='variation_category',
        ),
    ]
